dist: bionic

language: go

go:
  - 1.12

before_install:
  - pwd
  - git clone -b 'v0.3.3' --depth 1 https://github.com/pdfcpu/pdfcpu.git
  
script:
  - cd pdfcpu/cmd/pdfcpu
  - go install
  - pdfcpu version
  - GOOS=js GOARCH=wasm go build -o pdfcpu.wasm
  
after_script:
  - cd pdfcpu/cmd/pdfcpu
  - tar -czvf pdfcpu.tar.gz pdfcpu.wasm
  - wget http://gosspublic.alicdn.com/ossutil/1.6.14/ossutil64                           
  - chmod 755 ./ossutil64
  - ./ossutil64 -i ${AliyunAccessKey} -k ${AliyunAccessSecret} -e oss-cn-hangzhou.aliyuncs.com -f cp pdfcpu.tar.gz oss://gamelets/pub/   
